export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/checkout/cart',
  PAYMENT: '/checkout/payment',
  PRODUCTS: '/products',
  ORDERS: '/orders',
  CATEGORY: '/category',
  BUYER: '/buyer',
  SUPPLIER: '/supplier',
  TOWN_LEADER: '/town-leader',
};
