export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/checkout/cart',
  PAYMENT: '/checkout/payment',
  PAYMENT_SUCCESS: '/checkout/payment/success',
  PRODUCTS: '/products',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/detail/:slug',
  CATEGORY: '/category',
  BUYER: '/buyer',
  PROVIDER: '/provider',
  PROVIDER_ACCOUNT: '/provider',
  PROVIDER_REPORT: '/provider/report',
  PROVIDER_PRODUCTS: '/provider/products',
  PROVIDER_ADD_PRODUCT: '/provider/add-product',
  TOWN_LEADER: '/town-leader',
  TOWN_LEADER_WATCH: '/town-leader/watch',
  CATEGORY_GENRE: '/category/category1',
  FORGOT_PASSWORD: '/forgot-password',
};
